name: Docker Image CI

on:
  push:
    branches: [ "master-entw" ]
  pull_request:
    branches: [ "master-entw" ]

jobs:

  build:

    runs-on: github

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --pull tools/docker/noble --file Dockerfile --tag libreelec.noble:$(date +%s)
