name: Docker Image CI

on:
  push:
    branches: [ "master-entw" ]
  pull_request:
    branches: [ "master-entw" ]

jobs:

  build:

    runs-on: github
#    runs-on: self-hosted

    steps:
    -
      name: Build the Docker image
      uses: actions/checkout@v4
#      run: docker build ./tools/docker/noble --tag libreelec.noble:$(date +%s)
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build without push
      uses: docker/build-push-action@v6
      with:
        file: ./tools/docker/noble/Dockerfile
        push: false
        # tags: libreelec.noble:$(date +%s)
