name: Build Container for building EddictwareELEC images

on:
  workflow_dispatch:
  push:
    branches: [ "master-entw" ]
  pull_request:
    branches: [ "master-entw" ]

jobs:
  build:
#    runs-on: github
    runs-on: self-hosted
    env:
      BUILDKIT_PROGRESS: 'auto' #'plain' 'quiet'
    steps:
    - 
      name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash

    - 
      name: Get docker guid
      id: get-docker-guid
      run: |
        echo "docker-guid=$(id -u docker)" >> $GITHUB_OUTPUT
      shell: bash

    -
      name: Build the Docker image
      uses: actions/checkout@v4
      with:
        ref: 'master-entw'

    - 
      name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-multi-buildx-${{ github.ref_name }}-${{ steps.get-date.outputs.date }} #${{ github.sha }} ${{ github.ref_name }}
        restore-keys: |
          ${{ runner.os }}-multi-buildx-${{ github.ref_name }}-

    - name: Log in to (local/private) registry
      uses: docker/login-action@v3
      with:
        registry: "${{ secrets.REGISTRY_FQDN }}"
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PWD }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md
        buildkitd-config-inline: |
          debug = false
          [registry."${{ secrets.REGISTRY_FQDN }}"]
            http = false
            mirrors = ["localhost"]
        cleanup: true
#        buildkitd-flags: '"--progress ''plain''"'

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 10G

    -
      name: Build and export to (local/private) registry
      uses: docker/build-push-action@v6
      with:
        file: tools/docker/noble/Dockerfile
        load: true
        tags: eddict/eddictwareelec.noble
        build-args: |
          USER_UID=${{ steps.get-docker-guid.outputs.docker-guid }}
#          --progress=plain
#          DOCKER_BUILDKIT=0
        no-cache: false
        # cache-from: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_IMAGE_NAME }}.1:buildcache
        # cache-to: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_IMAGE_NAME }}.1:buildcache,mode=max
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

    - 
      name: Build EddictwareELEC image
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chown -R docker:docker $PWD
        docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
        docker run --rm \
          --log-driver none \
          --name "buildEddictwareELEC.noble" \
          -v $PWD:/build \
          -w /build \
          -e DISABLE_COLORS=yes \
          -e LOGCOMBINE=fail \
          -e MTIMMEDIATE=no \
          -e MTDEBUG=no \
          -e MTVERBOSE=no \
          -e MTPROGRESS=yes \
          -e PROJECT=RPi \
          -e DEVICE=RPi4 \
          -e ARCH=aarch64 \
          -e BUILDER_NAME=Eddict \
          -e BUILDER_VERSION="13.0-$(date +%Y%m%d)" \
          "${{ secrets.REGISTRY_FQDN }}/eddict/eddictwareelec.noble" PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:${PATH}" make image

    - 
      name: Build and push to (local/private) registry
      uses: docker/build-push-action@v6
      with:
        file: tools/docker/noble/Dockerfile
        push: true
        tags: "${{ secrets.REGISTRY_FQDN }}/eddict/eddictwareelec.noble"
        no-cache: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
