name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master-entw" ]
  pull_request:
    branches: [ "master-entw" ]

jobs:
  build:
#    runs-on: github
    runs-on: self-hosted
    steps:
    -
      name: Build the Docker image
      uses: actions/checkout@v4
      with:
        # Default: ${{ github.repository }}
        repository: ${{ github.repository }}
        ref: 'master-entw'
    # -
    #   name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."${{ secrets.REGISTRY_FQDN }}:${{ secrets.REGISTRY_PORT }}"]
            http = false
            mirrors = ["localhost:${{ secrets.REGISTRY_PORT }}"]
 #      run: docker build ./tools/docker/noble --tag libreelec.noble:$(date +%s)
    -
      name: Build and push to (local) registry
      uses: docker/build-push-action@v6
      with:
        file: tools/docker/noble/Dockerfile
        push: true
        tags: libreelec.noble #localhost:5000/name/app:latest
#        secrets: |
#          GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
    - 
      name: Inspect
      run: |
        docker buildx imagetools inspect localhost:${{ secrets.REGISTRY_PORT }}/name/libreelec.noble
