name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master-entw" ]
  pull_request:
    branches: [ "master-entw" ]

jobs:
  build:
#    runs-on: github
    runs-on: self-hosted
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: 'plain'
    steps:
    -
      name: Build the Docker image
      uses: actions/checkout@v4
      with:
        # Default: ${{ github.repository }}
        repository: ${{ github.repository }}
        ref: 'master-entw'
    # -
    #   name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKERHUB_USERNAME }}
  #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-multi-buildx-
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."${{ secrets.REGISTRY_FQDN }}:${{ secrets.REGISTRY_PORT }}"]
            http = false
            mirrors = ["localhost:${{ secrets.REGISTRY_PORT }}"]
        cleanup: false
        buildkitd-flags: --debug
        # Only worked for us with this option on 🤷‍♂️ https://github.com/docker/build-push-action/issues/608
        install: true
 #      run: docker build ./tools/docker/noble --tag libreelec.noble:$(date +%s)
    -
      name: Build and push to (local) registry
      uses: docker/build-push-action@v6
      with:
        file: tools/docker/noble/Dockerfile
        push: true
        tags: libreelec.noble #localhost:5000/name/app:latest
        build-args: |
          BUILDKIT_PROGRESS=plain
#        secrets: |
#          GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
        no-cache: false
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        # cache-from: type=registry,ref=${{vars.DOCKER_HUB_USERNAME}}/${{vars.DOCKER_HUB_IMAGE_NAME}}.1:buildcache
        # cache-to: type=registry,ref=${{vars.DOCKER_HUB_USERNAME}}/${{vars.DOCKER_HUB_IMAGE_NAME}}.1:buildcache,mode=max
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
    - 
      name: Inspect
      run: |
        docker buildx imagetools inspect localhost:${{ secrets.REGISTRY_PORT }}/name/libreelec.noble
